config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get 'songs', to: 'songs#index'
  # get 'songs/new', to: 'songs#new'
  # post 'songs', to: 'songs#create'
  get 'dashboard', to: 'dashboard#show', as: :dashboard

  # get 'songs/:id', to: 'songs#show'

  resources :songs, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:new, :create]
  end

  patch '/bookings/:id/approve', to: 'bookings#approve'
  patch '/bookings/:id/decline', to: 'bookings#decline'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :song

  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true
  validates :release_year, presence: true
  validates :album, presence: true
  # validates :available, default: true
  validates :price, presence: true
  belongs_to :user
  has_many :bookings

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_title_album_arist,
  against: [ :title, :album, :artist ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :songs
  has_many :bookings

  def inbound_bookings
    Booking.joins(:song).where('songs.user_id = ?', self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  protected

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

def new
  @booking = Booking.new
end

def create
  @booking = Booking.new(booking_params)
  @song = Song.find(params[:song_id])
  @booking.song = @song
  @booking.user = current_user
  # raise

  if @booking.save
    redirect_to dashboard_path, notice: "booking request received"
  else
    render 'songs/show', status: :unprocessable_entity
  end

end

def approve
  booking = Booking.find(params[:id])
  booking.status = 'accepted'
  booking.save
  redirect_to dashboard_path, notice: 'Booking accepted'
end

def decline
  booking = Booking.find(params[:id])
  booking.status = 'declined'
  booking.save
  redirect_to dashboard_path, notice: 'Booking declined'
end

private

def booking_params
  params.require(:booking).permit(:start_date, :end_date)
end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @user = current_user
    @my_songs = Song.where(user_id: @user.id)
    @my_purchases = Booking.includes(:song).where(user_id: @user)
    @my_songs.each do |song|
      song.bookings.each do |booking|
        if Date.today >= booking.start_date && Date.today <= booking.end_date && booking.status == "accepted"
          song.available = false
        else
          song.available = true
        end
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @user = current_user
      if params[:query].present?
        @songs = Song.where("title ILIKE ? OR album ILIKE ? OR artist ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%")
                     .where.not(user_id: @user.id)
      else
        @songs = Song.where.not(user_id: @user.id)
      end
  end

  def new
    @song = Song.new
  end

  def create
    # raise
    @user = current_user
    @song = Song.new(song_params)
    @song.user = @user
    if @song.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @song = Song.find(params[:id])
    @booking = Booking.new
    @bookings = @song.bookings
    @dates = @bookings.map do |booking|
      [ booking.start_date.to_s, booking.end_date.to_s ]
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :photo, :release_year, :artist, :album, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<%# to delete %>
<div class="container mb-3">
 <div class="row">
    <div class="col">
      <h1>My dashboard</h1>
    </div>
  </div>
<div class="row">
  <div class="col">
<div class="bg-white card-request px-3 py-3">
    <h4>My pending requests</h4>
    <% pending_inbound_bookings = current_user.inbound_bookings.where(status: 'pending') %>
    <% if !pending_inbound_bookings.empty? %>
      <% pending_inbound_bookings.each do |booking| %>
          <div class="d-flex align-items-center mb-1" style="border-bottom: 1px solid #adb5bd">
            <p class="flex-grow-1 mt-2">
            <strong><%= booking.user.first_name %></strong> has requested to book "<%= booking.song.title %>"
            from <%= booking.start_date %> to <%= booking.end_date %>
            </p>
            <div class='d-flex'>
              <%= form_with url: "/bookings/#{booking.id}/approve", method: :patch do |form|%>
                <%= form.submit "Approve", class: 'btn'%>
              <% end %>
              <%= form_with url: "/bookings/#{booking.id}/decline", method: :patch do |form|%>
                <%= form.submit "Decline", class: 'btn'%>
              <% end %>
            </div>
          </div>
      <% end %>
    <% else %>
      <div class="font-weight-light text-muted">
        No bookings for review
      </div>
    <% end %>
</div>
</div>
  </div>
  <div class="row mt-4">
    <div class="col">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <h2> My songs </h2>
        <%= link_to "Upload a new song", new_song_path, class: "btn btn-primary height:25%" %>
      </div>
        <% @my_songs.each do |song| %>
          <% if song.available == true %>
            <%= link_to song_path(song), class: 'card-product mb-3 d-flex' do %>
              <%= cl_image_tag song.photo.key %>
              <div class="card-product-infos">
                <h2> <%= song.title %> </h2>
                <p><%= song.album %> - <i><%= song.release_year %></i></p>
                <p class="bg-success-subtle rounded-pill text-center" style="width: 80px"> <%= song.available ? "Available" : "Booked" %> </p>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <% @my_songs.each do |song| %>
          <% if song.available == false %>
            <%= link_to song_path(song), class: 'card-product mb-3 d-flex bg-light' do %>
              <%= cl_image_tag song.photo.key %>
              <div class="card-product-infos">
                <h2> <%= song.title %> </h2>
                <p><%= song.album %> -  <i><%= song.release_year %></i></p>
                <p class="bg-warning-subtle rounded-pill text-center" style="width: 80px"> <%= song.available ? "Available" : "Booked" %></p>
              </div>
            <% end %>
          <% end %>
        <% end %>
    </div>
    <div class="col">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <h2> My purchases </h2>
        <%# <%= link_to "Browse all songs", songs_path, class: "btn btn-secondary height:25%" %>
      </div>
        <%# Empty state %>
        <% if current_user.bookings.empty?  %>
          <div style = " background-color: #e9e9e9; border-radius: 16px; text-align: center; padding: 50px;" >
            <h4 style="padding-bottom: 30px;">Your bookings will show here</h4>
            <%= link_to "Browse all songs", songs_path, class: "btn btn-secondary height:25%" %>
          </div>
          <% else %>
        <% end %>
        <% @my_purchases.each do |booking| %>
          <%= link_to song_path(booking.song), class: 'card-product mb-3 d-flex' do %>
            <%= cl_image_tag booking.song.photo.key %>
          <div class="card-product-infos">
              <h2> <%= booking.song.title %> </h2>
              <p><%= booking.song.album %> - <i><%= booking.song.release_year %></i></p>
              <p><%= booking.start_date %> to <%= booking.end_date %></p>
              <% if booking.status === "pending" %>
                  <p class="bg-warning-subtle rounded-pill text-center" style="width: 80px">Pending</p> <%# change this when booking.status is coded  %>
              <% elsif booking.status === "accepted" %>
                <p class="bg-success-subtle rounded-pill text-center" style="width: 80px">Accepted</p>
              <% else %>
                <p class="bg-secondary-subtle rounded-pill text-center" style="width: 80px">Declined</p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BorrowMySongie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>

  <body>
    <div style="min-height: calc(100vh - 100px);">
        <%= render "shared/navbar" %>
        <%= yield %>
    </div>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex justify-content-center align-items-center" style= "height: 80vh; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/premium-photo/platform-product-showcase-dark-background-with-colorful-musical-note_152359-929.jpg);">
  <div class="text-center">
    <h1>RentMyTune</h1>
    <p>Monetize Your Melodies and Find the Perfect Track for Any Project</p>
    <a class="btn btn-flat btn-primary my-3" href="<%= user_signed_in? ? '/dashboard' : '/users/sign_up' %>">Start Listening</a>
  </div>
</div>

<div class="footer d-flex justify-content-center align-items-center">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex align-items-center justify-content-between bg-white">

  <div class="footer-links align-items-center justify-content-between">
    <div class="footer-links d-flex align-items-center me-5">
      <i class="fa-solid fa-phone"></i>
      <p class="ms-2 mb-0">+1 (708) 352 647 9</p>
    </div>
    <div class="d-flex align-items-center">
      <i class="fa-regular fa-envelope"></i>
      <p class="ms-2 mb-0">hello@rentmytune.com</p>
    </div>
  </div>

  <div class="footer-links justify-content-right">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/songs", class: "navbar-brand" do %>
      <%= image_tag "Logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Upload a song", new_song_path, class: "nav-link" %>
          <li class="nav-item active dashboard", style="position: relative;">
            <%= link_to "My Dashboard", dashboard_path, class: "nav-link" %>
            <% if current_user.inbound_bookings.where(status: 'pending').exists?%>
              <span class="purple-dot"></span>
            <% end %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/inesperez", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/songs/_form.html.erb
<div data-controller="image-search" >
  <%= simple_form_for @song do |f| %>
  <div>
    <%= f.input :title, class:"col-auto", placeholder: 'Hero' %>
    <%= f.input :artist, input_html: {data: {image_search_target: "artist"}}, placeholder: 'Enrique Iglesias'%>
    <%= f.input :album, input_html: {data: {action: "change->image-search#searchImage"}}, placeholder: 'Escape' %>
    <%= f.input :release_year, label: 'Year', placeholder: '2001' %>
    <%= f.input :price, label: 'Price per day', placeholder: '£'%>
    <%= f.input :photo, as: :file %>
  </div>
    <%= f.button :submit, "Add song", class: "btn btn-primary" %>
  <% end %>
  <div class="container" data-image-search-target="display-image">
  </div>
</div>

app/views/songs/index.html.erb
<div class="container">
  <div class= "d-flex justify-content-between align-items-center">
    <h1>All songs</h1>
    <%= link_to "Upload a new song", new_song_path, class: "btn btn-primary height:25%" %>
  </div>
 <div class="songs-container p-2">
  <div class="row search">
    <div class="col-sm-12 my-3">
      <%= form_with url: songs_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-secondary" %>
      <% end %>
      </div>
  </div>
  <div class="all-songs">
    <% @songs.each do |song| %>
        <%= link_to song_path(song), class: 'card-product d-flex mb-2 align-items-start' do %>
            <%= cl_image_tag song.photo.key %>
            <div class="card-product-infos">
                <h2><%= song.title %></h2>
                <p><%= song.artist %> - <i><%= song.release_year %></i></p>
                <p>Yours for <strong>£<%= song.price %> </strong> per day</p>
            </div>
        <% end %>
    <% end %>
  </div>

 </div>

</div>

app/views/songs/new.html.erb
<div class="container card-new-song p-3 my-5 col-sm-5 justify-content-center">
  <h2>Upload a new song</h2>
  <%= render "songs/form", songs: @songs %>
</div>

app/views/songs/show.html.erb
<div class = "container mx-auto my-4">
  <div class ="card-tune">
    <div class="card-tune-infos" data-controller='player'>
      <div data-player-target='button' data-action='click->player#toggle' class='play-button'>
        <i data-player-target='playIcon' class="fa-solid fa-play fa-2xl icon"></i>
        <i data-player-target='playingIcon' class="fa-solid fa-spinner fa-spin icon fa-2xl d-none"></i>
        <div class="layer"></div>
        <% if @song.photo.key? %>
          <%= cl_image_tag @song.photo.key, height: 400, width: 400, crop: :fill %>
        <% end %>
      </div>
      <div data-player-target='iframeDiv' class='d-none'></div>
      </div>
      <div class="row" style="margin-left: 16px; margin-right: 16px">
        <h2 style="margin-top: 20px; margin-bottom: 40px;"><%= @song.title %> - <%= @song.release_year %> </h2>
        <div class="col">
          <p><strong>Artist:</strong> <%= @song.artist %></p>
          <p> <strong>Album:</strong> <%= @song.album %> </p>
        </div>
        <div class="col">
        <p><strong>Price per day:</strong> £<%= @song.price %></p>
        <p><strong>Owner:</strong> <%= @song.user.first_name %> <%= @song.user.last_name %></p></p>
        </div>
        <div> <strong> About:</strong> "<%= @song.title %>" is a widely recognized track that has captivated audiences around the world. With its compelling lyrics and unforgettable melody, it continues to be a standout in the music industry. From its initial release to the present day, "<%= @song.title %>" remains a testament to the artistry and creativity that defines popular music.</div>
    </div>
  </div>







<div data-controller = "toggle">
<%= link_to "Back to all songs", songs_path, :class => "btn btn-secondary", data: { toggle_target: "backButton" }%>
<% if @song.user_id != current_user.id %>
  <%= link_to "Book this song",  "#", :class => "btn btn-primary", data: { action: "click->toggle#fire", toggle_target: "rentButton"}%>

<% end %>


<!-- Set datepicker controller on the whole div -->
<div data-controller="datepicker" data-toggle-target="togglableElement" class="d-none" >
<h4>Choose your rental dates</h2>
<!-- Set datepicker controller on the whole div -->
  <div data-controller="datepicker">
    <!-- Add dates target to grab the @dates from the songs controller and pass to the stimulus controller-->
    <div data-datepicker-target="dates" data-dates="<%= @dates.to_json %>"></div>
    <%= simple_form_for [@song,@booking] do |f| %>
      <div>
        <%= f.input :start_date,
        as: :string,
        # <!-- Add datePicker target to the input -->
        input_html: { data: { datepicker_target: "datePicker", action: "change->datepicker#initFlatpickr"} }
        %>
        <%= f.input :end_date,
        as: :string,
        # <!-- Add datePicker target to the input -->
        input_html: { data: { datepicker_target: "datePicker" } }
        %>
      </div>
        <%= link_to "Back to all songs", songs_path, :class => "btn btn-secondary"%>
        <%= f.button :submit, "Request booking", class: "btn btn-primary" %>
      <% end %>

      </div>
    </div>
  </div>
</div>